Lesson 1: Upd docker-compose.yml
praisethedeviI/fefu-backend-3-6 pull request #1
Opened 2022-03-16 16:37 UTC by praisethedeviI

2022-03-23 02:31 UTC, chrn-feip requested changes

2022-03-23 02:31 UTC, chrn-feip commented on docker-compose.yml
> +        environment:
Это нужно не так делать. У вас есть файл .env.example, из которого при создании контейнеров делается .env. Как раз в .env вы прописываете все настройки (пароли, логины, порты, хосты и т.п.). 

Не нужно в коде засвечивать приватные данные. Оформите это всё аналогично переменным, используемым в pgsql. И объявите сами переменные с дефолтными или пустыми значениями в .env.example, добавьте в коммит.

2022-03-29 04:25 UTC, praisethedeviI commented
Обновил код, поправки имеются только с pgadmin. Прописал все настройки в локальном .env.

2022-03-30 13:11 UTC, chrn-feip requested changes
В ветке лишние коммиты и изменения из них. Обновите локальную ветку master, переключитесь на ветку с кодом ДЗ, сделайте git rebase master. В процессе решите конфликты, если будут. Проверьте по git log, что коммиты с ДЗ есть и они наверху в истории. Сделайте git push -f origin ветка. В итоге в PR должны остаться коммиты только по ДЗ. Т.е. в вашем случае один коммит, в котором добавлен конфиг для pgAdmin

2022-03-30 13:13 UTC, chrn-feip commented on docker-compose.yml
> +        environment:
Переменные вы завели, а где же они в .env.example?

2022-03-30 14:21 UTC, closed without merging