Lesson 8: Add products and attributes (web & API)
praisethedeviI/fefu-backend-3-6 pull request #10
Opened 2022-05-13 10:13 UTC by praisethedeviI

2022-05-17 10:27 UTC, chrn-feip requested changes

2022-05-17 10:27 UTC, chrn-feip commented on routes/api.php
> +    Route::get('product/list', [ProductController::class, 'index'])->name('product.list');
Для API методов name обычно не задаётся, только точечно при необходимости использования. В проекте именованные API-роуты не используются.

2022-05-17 10:27 UTC, chrn-feip commented on app/OpenApi/Schemas/ProductSchema.php
> +                Schema::string('category'),
Почему строка, а не объект?

2022-05-17 10:27 UTC, chrn-feip commented on app/Http/Resources/ProductResource.php
> +            'category' => $this->productCategory->name,
Лучше передавать как вложенный ресурс, например, для того, чтобы дать ссылку на всю категорию, в которой товар лежит.

2022-05-17 10:27 UTC, chrn-feip commented on app/Http/Resources/ProductFromCatalogResource.php
> +class ProductFromCatalogResource extends JsonResource
ListProductResource

2022-05-17 10:27 UTC, chrn-feip commented on app/Http/Resources/ProductResource.php
> +class ProductResource extends JsonResource
ProductDetailsResource или DetailedProductResource

2022-05-17 10:27 UTC, chrn-feip commented on app/Http/Controllers/Api/ProductController.php
> +        $categories = $categoryQuery->get();
Некорректно. Если у вас слаг в запрос передан, то уже выполнится firstOrFail, который в случае успеха вернёт инстанс модели. К тому же вы его никуда не сохранили, это конечный метод конструктора запроса, его результат нужно в переменную вычитать. Сделайте тут get, в else ветке уберите firstOrFail, а внутри getTreeProductBuilder проверьте, что переданная коллекция категорий не пуста. Если пуста, то бросьте исключение.

2022-05-17 10:27 UTC, chrn-feip commented on app/Enums/AbstractEnum.php
> +class AbstractEnum
abstract class

2022-05-17 10:27 UTC, chrn-feip commented on app/Enums/ProductAttributeType.php
> +class ProductAttributeType extends AbstractEnum
final class

2022-05-17 10:27 UTC, chrn-feip commented on api-docs.json
> +                "summary": "Display products of specified catalog.",
У нас один каталог, он не может быть specified. Вот категорий в нём много. Display a paginated list of category products.

2022-05-17 10:49 UTC, praisethedeviI commented on app/Enums/AbstractEnum.php
> +class AbstractEnum
@chrn-feip не понял, что здесь требуется

2022-05-17 10:49 UTC, praisethedeviI commented on app/Enums/ProductAttributeType.php
> +class ProductAttributeType extends AbstractEnum
и что здесь, тоже

2022-05-17 10:51 UTC, praisethedeviI commented on app/Enums/AbstractEnum.php
> +class AbstractEnum
Все, сообразил)

2022-05-18 02:52 UTC, chrn-feip requested changes

2022-05-18 02:52 UTC, chrn-feip commented on app/Http/Controllers/Web/CatalogController.php
>              $query->where('slug', $slug)->first();
Снова нет.  Какой результат вызова у first? Инстанс модели или null. Это конечный результат, уже не конструктор запросов. Оставьте тут только where. За if у вас уже есть конечный метод get, который возвращает коллекцию - пустую или с одним/несколькими объектами. И результат этого get сохранён в переменную, как и нужно.

2022-05-18 02:52 UTC, chrn-feip commented on app/Models/ProductCategory.php
> +            abort(404);
1. Из модели мы не бросать http исключений, это прерогатива контроллеров. 
2. Причём тут 404? Это статус о том, что запрошенный ресурс не найден. У нас же другая ситуация. Сделайте тут throw new Exception('Empty categories collection');

2022-05-18 05:35 UTC, praisethedeviI commented on app/Models/ProductCategory.php
> +            abort(404);
@chrn-feip абортить 422 кодом внутри контроллера в try catch?

2022-05-18 09:48 UTC, chrn-feip commented on app/Models/ProductCategory.php
> +            abort(404);
Да

2022-05-18 09:54 UTC, chrn-feip requested changes

2022-05-18 09:54 UTC, chrn-feip commented on app/Models/ProductCategory.php
> +use mysql_xdevapi\Exception;
Это лишнее
use Exception;

2022-05-18 09:54 UTC, chrn-feip commented on app/Models/ProductCategory.php
> +            throw new \Exception('Empty categories collection');
И тут тогда не нужен слеш

2022-05-18 09:54 UTC, chrn-feip commented on app/Http/Controllers/Api/ProductController.php
> +        $products = ProductCategory::getTreeProductBuilder($categories)
А тут где abort(422, $exception->getMessage())?

2022-05-18 09:54 UTC, chrn-feip commented on app/Http/Controllers/Web/CatalogController.php
> +            abort(422);
Тоже с текстом пойманного исключения

2022-05-18 09:54 UTC, praisethedeviI commented on app/Models/ProductCategory.php
> +            abort(404);
Сейчас допишу в API контроллере и сделаю force push

2022-05-18 09:55 UTC, praisethedeviI commented on app/Models/ProductCategory.php
> +use mysql_xdevapi\Exception;
Случайно добавилось при выборе не того класса

2022-05-18 09:57 UTC, praisethedeviI commented
@chrn-feip все исправил и добавил

2022-05-18 10:07 UTC, merged