Lesson 9: Add search, sorting, filters to catalog (web & api)
praisethedeviI/fefu-backend-3-6 pull request #11
Opened 2022-05-13 16:20 UTC by praisethedeviI

2022-05-15 08:12 UTC, tonighty requested changes

2022-05-15 08:12 UTC, tonighty commented on app/Http/Controllers/Api/ProductController.php
> +        ProductFilter::build($productQuery, $requestData['filters'] ?? []);
фильтры, которые ты тут сбилдил, нужно на фронт отправлять

2022-05-15 14:14 UTC, praisethedeviI commented on app/Http/Controllers/Api/ProductController.php
> +        ProductFilter::build($productQuery, $requestData['filters'] ?? []);
Добавил

2022-05-17 07:47 UTC, tonighty approved these changes

2022-05-18 10:08 UTC, chrn-feip commented
@praisethedeviI надо обновить PR

2022-05-18 10:13 UTC, chrn-feip commented
Конфликты не забудьте решить

2022-05-18 10:18 UTC, praisethedeviI commented
@chrn-feip сделал rebase в origin/master

2022-05-18 10:22 UTC, chrn-feip requested changes

2022-05-18 10:22 UTC, chrn-feip commented on routes/api.php
> +Route::get('products', [ProductController::class, 'index']);
А это зачем? У вас же есть уже с предыдущего БД роут, который возвращает список товаров, в т.ч. без слага категориии.

2022-05-18 10:24 UTC, praisethedeviI commented on routes/api.php
> +Route::get('products', [ProductController::class, 'index']);
По заданию надо было сделать такой роут

2022-05-18 10:27 UTC, chrn-feip commented on routes/api.php
> +Route::get('products', [ProductController::class, 'index']);
@tonighty а зачем?

2022-05-18 12:20 UTC, merged