Lesson 3
praisethedeviI/fefu-backend-3-6 pull request #5
Opened 2022-04-09 13:57 UTC by praisethedeviI

2022-04-09 22:10 UTC, tonighty commented
Тебе rebase нужно сделать

2022-04-09 22:11 UTC, tonighty requested changes

2022-04-09 22:11 UTC, tonighty commented on app/Http/Controllers/Web/NewsController.php
> +    public function __invoke(Request $request, string $slug)
у новостей должны быть и список (пагинированный), и отдельная новость

2022-04-10 02:17 UTC, praisethedeviI commented on app/Http/Controllers/Web/NewsController.php
> +    public function __invoke(Request $request, string $slug)
Методы, возвращающие пагинированный список `index` и отдельную новость `show`, реализованы в API контроллере новостей app/Http/Controllers/Api/NewsController.php

2022-04-10 05:31 UTC, praisethedeviI commented on app/Http/Controllers/Web/NewsController.php
> +    public function __invoke(Request $request, string $slug)
Исправил

2022-04-10 09:32 UTC, tonighty requested changes

2022-04-10 09:32 UTC, tonighty commented on app/Http/Controllers/Web/NewsListController.php
> +class NewsListController extends Controller
не нужно на каждый пук создавать контроллер))

в Web/NewsController добавь index и show, как в апи контроллере сделано

2022-04-10 10:42 UTC, praisethedeviI commented on app/Http/Controllers/Web/NewsListController.php
> +class NewsListController extends Controller
Исправил

2022-04-10 10:44 UTC, tonighty approved these changes

2022-04-10 10:45 UTC, merged